
optimization:
  COBYLA:
    method: "COBYLA"
    tol: 1.0e-7
    options:
      rhobeg: 1.570796
      maxiter: 1000
      disp: false
  Nelder-Mead:
    method: "Nelder-Mead"
    tol: 1.0e-7
    options:
      maxiter: 1000
      xatol: 1.0e-4
      fatol: 1.0e-4
      disp: false
  L-BFGS-B:
    method: "L-BFGS-B"
    tol: 1.0e-7
    options:
      maxiter: 1000
      ftol: 1.0e-8
      disp: false
  Powell:
    method: "Powell"
    tol: 1.0e-7
    options:
      maxiter: 1000
      ftol: 1.0e-7
      disp: false

simulation:
  q_points: 100

minimize:
  trial: 2
  q_points: 2
  lambda_val: 1

flags:
  save_data: true
  use_dummy_slm: false

columns:
  theory:
    - overlap
    - fixed rate
    - success rate
    - error rate
    - failure rate
  raw data:
    - overlap
    - trial
    - fixed rate
    - success rate
    - error rate
    - failure rate
    - lagrangian
    - lambda
    - method
    - maxiter
  sim data:
    - overlap
    - trial
    - fixed rate
    - success rate
    - error rate
    - failure rate
    - lagrangian
    - lambda
    - method
    - maxiter
