columns:
  raw data:
  - timestamp
  - optimizer
  - lamda_val
  - fixed rate
  - history
  - raw_data
  sim data:
  - timestamp
  - optimizer
  - lamda_val
  - fixed rate
  - history
  - raw_data
  theory:
  - overlap
  - fixed rate
  - success rate
  - error rate
  - failure rate
devices:
  slm:
    beam_w0: 0.0008
    pixel_pitch: 8.0e-06
    res:
    - 1920
    - 1080
  timetagger:
    binwidth: 50
    cw: 50
    delay:
    - 29443
    - 0
    n_value: 2
flags:
  save_data: true
  use_dummy_slm: false
minimize:
  dim: 3
  lambda_val: 1
  optimizer: Adam
  overlap: 0.75
  q_points:
  - 0.0
  - 0.1875
  - 0.3750
  - 0.5625
  - 0.75
  trial: 100
optimization:
  COBYLA:
    method: COBYLA
    options:
      disp: false
      maxiter: 10000
      rhobeg: 1.570796
    tol: 0.01
  Nelder-Mead:
    method: Nelder-Mead
    options:
      disp: false
      fatol: 0.0001
      maxiter: 1000
      xatol: 0.0001
    tol: 0.01
  BFGS:
    method: BFGS
    options:
      disp: false
      maxiter: 1000
    tol: 0.01
  Adam:
    method: Adam
    options:
      disp: false
      maxiter: 1000
    tol: 0.01
simulation:
  q_points: 100
