columns:
  raw data:
  - overlap
  - trial
  - fixed rate
  - success rate
  - error rate
  - failure rate
  - lagrangian
  - lambda
  - method
  - maxiter
  sim data:
  - overlap
  - trial
  - fixed rate
  - success rate
  - error rate
  - failure rate
  - lagrangian
  - lambda
  - method
  - maxiter
  theory:
  - overlap
  - fixed rate
  - success rate
  - error rate
  - failure rate
devices:
  slm:
    beam_w0: 0.0008
    pixel_pitch: 8.0e-06
    res:
    - 1920
    - 1080
  timetagger:
    binwidth: 50
    cw: 50
    delay:
    - 29443
    - 0
    n_value: 2
flags:
  save_data: true
  use_dummy_slm: false
minimize:
  dim: 4
  lambda_val: 1.0
  optimizer: COBYLA
  overlap: 0.75
  q_points:
  - 0.0
  - 0.25
  - 0.5
  - 0.75
  trial: 5
optimization:
  COBYLA:
    method: COBYLA
    options:
      disp: false
      maxiter: 10000
      rhobeg: 1.570796
    tol: 0.01
  L-BFGS-B:
    method: L-BFGS-B
    options:
      disp: false
      ftol: 1.0e-08
      maxiter: 1000
    tol: 1.0e-07
  Nelder-Mead:
    method: Nelder-Mead
    options:
      disp: false
      fatol: 0.0001
      maxiter: 1000
      xatol: 0.0001
    tol: 0.01
  Powell:
    method: Powell
    options:
      disp: false
      ftol: 1.0e-07
      maxiter: 1000
    tol: 1.0e-07
simulation:
  q_points: 100
