columns:
  raw data:
  - overlap
  - trial
  - fixed rate
  - success rate
  - error rate
  - failure rate
  - lagrangian
  - lambda
  - method
  - maxiter
  sim data:
  - overlap
  - trial
  - fixed rate
  - success rate
  - error rate
  - failure rate
  - lagrangian
  - lambda
  - method
  - maxiter
  theory:
  - overlap
  - fixed rate
  - success rate
  - error rate
  - failure rate
devices:
  slm:
  - - 1920
    - 1080
  - 8e-6
  - 8e-4
  timetagger:
  - 500
  - 50
  - 2
  - - 29443
    - 0
flags:
  activate:
    toy_example_1: false
    toy_example_2: false
    toy_example_3: false
  save_data: true
  use_dummy_slm: false
minimize:
  lambda_val: 1
  optimizer: COBYLA
  q_points: 2
  trial: 2
optimization:
  COBYLA:
    method: COBYLA
    options:
      disp: false
      maxiter: 1000
      rhobeg: 1.570796
    tol: 1.0e-07
  L-BFGS-B:
    method: L-BFGS-B
    options:
      disp: false
      ftol: 1.0e-08
      maxiter: 1000
    tol: 1.0e-07
  Nelder-Mead:
    method: Nelder-Mead
    options:
      disp: false
      fatol: 0.0001
      maxiter: 1000
      xatol: 0.0001
    tol: 1.0e-07
  Powell:
    method: Powell
    options:
      disp: false
      ftol: 1.0e-07
      maxiter: 1000
    tol: 1.0e-07
simulation:
  q_points: 100
