settings:
- dim: 3
  lambda_val: 1.0
  optimizer: COBYLA
  overlap: 0.75
  q_points: 1
  tol: 0.01
  trial: 1
- dim: 3
  lambda_val: 1.0
  optimizer: Nelder-Mead
  overlap: 0.75
  q_points: 1
  tol: 0.01
  trial: 1
