settings:
- dim: 3
  lambda_val: 1.0
  optimizer: COBYLA
  overlap: 0.5
  q_points: 10
  tol: 0.1
  trial: 100
- dim: 3
  lambda_val: 1.0
  optimizer: COBYLA
  overlap: 0.5
  q_points: 10
  tol: 0.01
  trial: 100
- dim: 3
  lambda_val: 1.0
  optimizer: COBYLA
  overlap: 0.75
  q_points: 10
  tol: 0.1
  trial: 100
- dim: 3
  lambda_val: 1.0
  optimizer: COBYLA
  overlap: 0.75
  q_points: 10
  tol: 0.01
  trial: 100
- dim: 4
  lambda_val: 0.87
  optimizer: COBYLA
  overlap: 0.5
  q_points: 10
  tol: 0.1
  trial: 100
- dim: 4
  lambda_val: 0.87
  optimizer: COBYLA
  overlap: 0.5
  q_points: 10
  tol: 0.01
  trial: 100
- dim: 4
  lambda_val: 0.87
  optimizer: COBYLA
  overlap: 0.75
  q_points: 10
  tol: 0.1
  trial: 100
- dim: 4
  lambda_val: 0.87
  optimizer: COBYLA
  overlap: 0.75
  q_points: 10
  tol: 0.01
  trial: 100
- dim: 5
  lambda_val: 0.8
  optimizer: COBYLA
  overlap: 0.5
  q_points: 10
  tol: 0.1
  trial: 100
- dim: 5
  lambda_val: 0.8
  optimizer: COBYLA
  overlap: 0.5
  q_points: 10
  tol: 0.01
  trial: 100
- dim: 5
  lambda_val: 0.8
  optimizer: COBYLA
  overlap: 0.75
  q_points: 10
  tol: 0.1
  trial: 100
- dim: 5
  lambda_val: 0.8
  optimizer: COBYLA
  overlap: 0.75
  q_points: 10
  tol: 0.01
  trial: 100
- dim: 3
  lambda_val: 1.0
  optimizer: Nelder-Mead
  overlap: 0.5
  q_points: 10
  tol: 0.1
  trial: 100
- dim: 3
  lambda_val: 1.0
  optimizer: Nelder-Mead
  overlap: 0.5
  q_points: 10
  tol: 0.01
  trial: 100
- dim: 3
  lambda_val: 1.0
  optimizer: Nelder-Mead
  overlap: 0.75
  q_points: 10
  tol: 0.1
  trial: 100
- dim: 3
  lambda_val: 1.0
  optimizer: Nelder-Mead
  overlap: 0.75
  q_points: 10
  tol: 0.01
  trial: 100
- dim: 4
  lambda_val: 0.87
  optimizer: Nelder-Mead
  overlap: 0.5
  q_points: 10
  tol: 0.1
  trial: 100
- dim: 4
  lambda_val: 0.87
  optimizer: Nelder-Mead
  overlap: 0.5
  q_points: 10
  tol: 0.01
  trial: 100
- dim: 4
  lambda_val: 0.87
  optimizer: Nelder-Mead
  overlap: 0.75
  q_points: 10
  tol: 0.1
  trial: 100
- dim: 4
  lambda_val: 0.87
  optimizer: Nelder-Mead
  overlap: 0.75
  q_points: 10
  tol: 0.01
  trial: 100
- dim: 5
  lambda_val: 0.8
  optimizer: Nelder-Mead
  overlap: 0.5
  q_points: 10
  tol: 0.1
  trial: 100
- dim: 5
  lambda_val: 0.8
  optimizer: Nelder-Mead
  overlap: 0.5
  q_points: 10
  tol: 0.01
  trial: 100
- dim: 5
  lambda_val: 0.8
  optimizer: Nelder-Mead
  overlap: 0.75
  q_points: 10
  tol: 0.1
  trial: 100
- dim: 5
  lambda_val: 0.8
  optimizer: Nelder-Mead
  overlap: 0.75
  q_points: 10
  tol: 0.01
  trial: 100
